### PR TITLE
Run rustfmt

### PR DESCRIPTION
**Pull request by steveklabnik**
I ran this through rustfmt and it did a pretty good job of changing the
formatting to what I'd do.

### CODE REVIEW

**Comment by steveklabnik** [comment]
Okay! This is all the PRs I have for you for now. :)

I'm sure there's still some things that could be cleaned up, let's see what others say.

**Comment by cgag** [comment]
Being able to have a standard formatting is probably worth conforming, but I did prefer the short match arms on a single line.  Oh well. 

Thanks again.

**Comment by steveklabnik** [comment]
Yeah, that is one in which I'm like 50/50.

**Comment by cgag** [comment]
I seriously appreciate all these PRs, that was incredibly helpful.  You're doing really good work making the Rust community a welcoming place.

**Comment by steveklabnik** [comment]
Thank you! It's also good practice :)

**Comment by lambda** [comment]
@cgag I've sent a pull request that moves these match arms back to being single-line without being "fixed" by rustfmt. You can have just a bare expression, delimited by a comma, as a match arm, rather than a whole block, and rustfmt doesn't break that up onto multiple lines.

**Pull request merged**
