### PR TITLE
2020update

### PR DESCRIPTION
**Pull request by xyproto**
* Update Cargo configuration and source files so that it builds with the latest version of Rust and Cargo
* Require 2 words that are hard to type instead of 4 words that are easy.
* The "hard words" are from a list I found online over words that people often type incorrectly. This change may train them (and me) to more often type this words correctly.
* Minor changes to `.gitignore` and `README.md`.

Thanks for creating `hostblock`, it's key to my productivity when working from home!

### CODE REVIEW

**Comment by xyproto** [comment]
This might also be related to #8.

**Comment by jappeace** [comment]
cool thanks, I think this is dead though.

**Comment by xyproto** [comment]
@cgag Is this project dead?

**Comment by cgag** [comment]
I still use it but never really look at this repo (I feel like I never got any notifications from it) and never actually thought about updating it.  I'll take a look at this now. Thanks a bunch and sorry for ignoring you.

**Comment by xyproto** [comment]
Cool, thanks for merging! :slightly_smiling_face:

**Pull request merged**
